'use client';
import './globals.css'
import NavBar from '@/components/NavBar'
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "use-shopping-cart";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider shouldPersist={true} >
          <SessionProvider>
            <NavBar />
            {children}
          </SessionProvider>
        </CartProvider>
      </body>
    </html>
  )
}
